import { InstagramProfile, InstagramMediaItem, AccountPerformanceSummary } from '@/types';

export interface DemoCreatorProfile {
  profile: InstagramProfile;
  media: InstagramMediaItem[];
  performance: AccountPerformanceSummary;
}

export const DEMO_CREATORS: Record<string, DemoCreatorProfile> = {
  'tech-ai': {
    profile: {
      id: 'demo_creator_tech_01',
      username: 'alexrivera_ai',
      name: 'Alex Rivera | AI & Automation',
      biography: '⚡ Helping 50,000+ humans 10x their output with AI & modern workflows\n🚀 Ex-Stripe Engineer\n📥 Weekly prompt breakdown 👇',
      profile_picture_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      followers_count: 54300,
      follows_count: 420,
      media_count: 148,
      account_type: 'CREATOR',
      is_demo: true,
    },
    performance: {
      totalFollowers: 54300,
      avgEngagementRate: 5.4,
      avgSavesPerPost: 1840,
      avgReachPerPost: 42600,
      saveToReachRatio: 4.3,
      topPerformingFormat: 'CAROUSEL',
      formatBreakdown: {
        reels: { count: 6, avgEngagement: 5.1 },
        carousels: { count: 5, avgEngagement: 6.8 },
        images: { count: 1, avgEngagement: 2.1 },
      },
      bestPostingHours: [
        { hour: '11:00 AM', day: 'Tuesday', engagementScore: 94 },
        { hour: '2:30 PM', day: 'Thursday', engagementScore: 98 },
        { hour: '7:00 PM', day: 'Sunday', engagementScore: 88 },
      ],
    },
    media: [
      {
        id: 'media_tech_1',
        caption: 'Stop using ChatGPT like a google search bar. Here are 5 prompt formulas that will generate actual executive-level strategy docs in 30 seconds. Bookmark this before you lose it 💾\n\n#aitools #chatgpt #productivity #techtrends #promptengineering',
        media_type: 'CAROUSEL_ALBUM',
        permalink: 'https://instagram.com/p/demo1',
        timestamp: '2026-08-30T14:30:00Z',
        like_count: 4210,
        comments_count: 312,
        insights: {
          reach: 68400,
          impressions: 89000,
          saved: 3950,
          shares: 1420,
          engagement: 5942,
        },
      },
      {
        id: 'media_tech_2',
        caption: 'The tool that just replaced 4 paid SaaS subscriptions in my stack. It auto-transcribes, cleans up, and formats your video podcasts into 10 multi-platform clips in 4 minutes. Link in bio.\n\n#aitools #saas #creatorlife #videoediting #automation',
        media_type: 'VIDEO',
        permalink: 'https://instagram.com/p/demo2',
        timestamp: '2026-08-27T17:00:00Z',
        like_count: 3180,
        comments_count: 245,
        insights: {
          reach: 52100,
          impressions: 64200,
          saved: 1820,
          shares: 890,
          engagement: 4315,
        },
      },
      {
        id: 'media_tech_3',
        caption: '3 mistakes beginners make when building their first autonomous AI agent. Slide 3 is the most common reason your API bill hits $200 overnight. 🛑\n\n#softwareengineer #techfounders #aiagents #codingtips #tech',
        media_type: 'CAROUSEL_ALBUM',
        permalink: 'https://instagram.com/p/demo3',
        timestamp: '2026-08-24T11:00:00Z',
        like_count: 5120,
        comments_count: 408,
        insights: {
          reach: 84300,
          impressions: 104000,
          saved: 4890,
          shares: 2110,
          engagement: 7638,
        },
      },
      {
        id: 'media_tech_4',
        caption: 'My minimalist workspace desk setup for 2026. Wireless everything, custom split mechanical keyboard, and dual 4K OLED screens. What would you change?\n\n#desksetup #minimalism #workspace #deskgoals #workfromhome',
        media_type: 'IMAGE',
        permalink: 'https://instagram.com/p/demo4',
        timestamp: '2026-08-21T18:30:00Z',
        like_count: 1490,
        comments_count: 86,
        insights: {
          reach: 22000,
          impressions: 26500,
          saved: 410,
          shares: 95,
          engagement: 1671,
        },
      },
      {
        id: 'media_tech_5',
        caption: 'How to build your second brain using Notion & Claude 3.5 in under 15 minutes. Step by step walkthrough on screen. Watch until the end for the free database template. 🧠⚡\n\n#secondbrain #notiontemplate #notionhacks #productivitytips #organization',
        media_type: 'VIDEO',
        permalink: 'https://instagram.com/p/demo5',
        timestamp: '2026-08-18T13:15:00Z',
        like_count: 6300,
        comments_count: 540,
        insights: {
          reach: 98000,
          impressions: 122000,
          saved: 5600,
          shares: 3100,
          engagement: 9940,
        },
      },
    ],
  },
  'fitness-wellness': {
    profile: {
      id: 'demo_creator_fit_02',
      username: 'elenafit_flow',
      name: 'Elena Rostova | Mobility & Strength',
      biography: '🧘‍♀️ Fix your posture & build functional athletic strength\n🥗 120g+ Protein daily without boring chicken & rice\n🏆 Certified Strength Coach | 100k+ transformed',
      profile_picture_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
      followers_count: 114200,
      follows_count: 310,
      media_count: 312,
      account_type: 'CREATOR',
      is_demo: true,
    },
    performance: {
      totalFollowers: 114200,
      avgEngagementRate: 6.8,
      avgSavesPerPost: 3910,
      avgReachPerPost: 98000,
      saveToReachRatio: 3.98,
      topPerformingFormat: 'REELS',
      formatBreakdown: {
        reels: { count: 8, avgEngagement: 7.9 },
        carousels: { count: 3, avgEngagement: 4.5 },
        images: { count: 1, avgEngagement: 2.8 },
      },
      bestPostingHours: [
        { hour: '7:30 AM', day: 'Monday', engagementScore: 92 },
        { hour: '6:00 PM', day: 'Wednesday', engagementScore: 96 },
        { hour: '9:00 AM', day: 'Saturday', engagementScore: 90 },
      ],
    },
    media: [
      {
        id: 'media_fit_1',
        caption: 'If your lower back hurts every time you sit at your computer for more than 2 hours, do this 3-minute hip flexor release right now. Save for later 📌\n\n#lowerbackpain #mobilityroutine #deskworker #posturecorrection #stretching',
        media_type: 'VIDEO',
        permalink: 'https://instagram.com/p/fit1',
        timestamp: '2026-08-31T07:30:00Z',
        like_count: 9400,
        comments_count: 420,
        insights: {
          reach: 142000,
          impressions: 185000,
          saved: 8400,
          shares: 4300,
          engagement: 14120,
        },
      },
      {
        id: 'media_fit_2',
        caption: 'High Protein Salted Caramel Overnight Oats 🍨 (42g Protein / 410 Calories). Prep this on Sunday night and breakfast is ready for the entire week.\n\n#highproteinmeals #mealprepmonday #healthydessert #overnightoats #macros',
        media_type: 'CAROUSEL_ALBUM',
        permalink: 'https://instagram.com/p/fit2',
        timestamp: '2026-08-28T12:00:00Z',
        like_count: 7200,
        comments_count: 310,
        insights: {
          reach: 89000,
          impressions: 110000,
          saved: 6100,
          shares: 2200,
          engagement: 9710,
        },
      },
    ],
  },
  'fashion-luxury': {
    profile: {
      id: 'demo_creator_fashion_03',
      username: 'marcusvance_style',
      name: 'Marcus Vance | Tailoring & Minimalist Style',
      biography: '👔 Elevating men’s everyday wardrobe through timeless silhouettes\n📍 London / Milan\n✨ Curated aesthetic & capsule wardrobe guides',
      profile_picture_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
      followers_count: 86400,
      follows_count: 512,
      media_count: 240,
      account_type: 'CREATOR',
      is_demo: true,
    },
    performance: {
      totalFollowers: 86400,
      avgEngagementRate: 4.2,
      avgSavesPerPost: 2150,
      avgReachPerPost: 64000,
      saveToReachRatio: 3.36,
      topPerformingFormat: 'CAROUSEL',
      formatBreakdown: {
        reels: { count: 5, avgEngagement: 3.9 },
        carousels: { count: 6, avgEngagement: 5.4 },
        images: { count: 1, avgEngagement: 3.1 },
      },
      bestPostingHours: [
        { hour: '12:30 PM', day: 'Friday', engagementScore: 91 },
        { hour: '5:00 PM', day: 'Sunday', engagementScore: 97 },
      ],
    },
    media: [
      {
        id: 'media_fash_1',
        caption: '5 color combinations that instantly make an outfit look 10x more expensive (without spending luxury prices). Notice how navy + oatmeal breaks the monochrome boredom.\n\n#menswear #oldmoneyaesthetic #quietluxury #capsulewardrobe #outfitinspo',
        media_type: 'CAROUSEL_ALBUM',
        permalink: 'https://instagram.com/p/fash1',
        timestamp: '2026-08-30T17:00:00Z',
        like_count: 5400,
        comments_count: 290,
        insights: {
          reach: 78000,
          impressions: 96000,
          saved: 4900,
          shares: 1600,
          engagement: 7290,
        },
      },
    ],
  },
  'travel-food': {
    profile: {
      id: 'demo_creator_travel_04',
      username: 'nomadfoodie_diaries',
      name: 'Maya & Liam | Hidden Cafes & Global Food',
      biography: '🍜 Chasing Michelin street food & scenic boutique stays in 42+ countries\n✈️ Tokyo 🇯🇵 ➔ Rome 🇮🇹 ➔ Bangkok 🇹🇭\n👇 Our secret food map guides',
      profile_picture_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80',
      followers_count: 198500,
      follows_count: 640,
      media_count: 520,
      account_type: 'CREATOR',
      is_demo: true,
    },
    performance: {
      totalFollowers: 198500,
      avgEngagementRate: 7.4,
      avgSavesPerPost: 6400,
      avgReachPerPost: 210000,
      saveToReachRatio: 3.05,
      topPerformingFormat: 'REELS',
      formatBreakdown: {
        reels: { count: 9, avgEngagement: 8.4 },
        carousels: { count: 2, avgEngagement: 5.1 },
        images: { count: 1, avgEngagement: 3.5 },
      },
      bestPostingHours: [
        { hour: '1:00 PM', day: 'Saturday', engagementScore: 99 },
        { hour: '8:00 PM', day: 'Friday', engagementScore: 95 },
      ],
    },
    media: [
      {
        id: 'media_travel_1',
        caption: 'We found a 90-year-old udon master tucked inside a quiet Kyoto back-alley with only 6 wooden seats. The broth takes 18 hours to simmer. Add this to your Japan bucket list immediately 🇯🇵🍜\n\n#kyotofood #japanbucketlist #tokyofoodie #hiddenfoodgems #traveljapan',
        media_type: 'VIDEO',
        permalink: 'https://instagram.com/p/travel1',
        timestamp: '2026-08-29T13:00:00Z',
        like_count: 18400,
        comments_count: 820,
        insights: {
          reach: 320000,
          impressions: 410000,
          saved: 19800,
          shares: 12400,
          engagement: 39020,
        },
      },
    ],
  },
};
