'use client';

import React, { useState } from 'react';
import { AIContentStrategyReport, InstagramProfile, AccountPerformanceSummary } from '@/types';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Printer, Copy, Check, FileDown } from 'lucide-react';
import confetti from 'canvas-confetti';

interface ExportModalProps {
  report: AIContentStrategyReport | null;
  profile: InstagramProfile | null;
  performance: AccountPerformanceSummary | null;
  onClose: () => void;
}

export default function ExportModal({ report, profile, performance, onClose }: ExportModalProps) {
  const [copiedMd, setCopiedMd] = useState(false);

  if (!report || !profile) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleCopyMarkdown = () => {
    const md = `# Instagram Growth Strategy Report: @${profile.username}
Generated by InstaPulse AI on ${new Date(report.generatedAt).toLocaleDateString()}

## 1. Creator Profile & Niche Classification
- **Handle:** @${profile.username}
- **Followers:** ${profile.followers_count.toLocaleString()}
- **Primary Category:** ${report.detectedNiche.primaryCategory}
- **Sub-Niche:** ${report.detectedNiche.subNiche}
- **Audience Persona:** ${report.detectedNiche.targetAudiencePersona}
- **Content Tone:** ${report.detectedNiche.contentTone}

## 2. Performance Audit
- **Avg Engagement Rate:** ${performance?.avgEngagementRate}%
- **Save-to-Reach Ratio:** ${performance?.saveToReachRatio}%
- **Top Performing Format:** ${performance?.topPerformingFormat}

### Strengths:
${report.performanceAudit.strengths.map(s => `- **${s.title}**: ${s.description} (${s.metricProof})`).join('\n')}

### Gaps to Fix:
${report.performanceAudit.gapsToFix.map(g => `- **${g.title}**: ${g.description}\n  *Action:* ${g.fixAction}`).join('\n')}

## 3. Recommended Viral Content Concepts
${report.viralRecommendations.map((v, i) => `
### Concept ${i+1}: ${v.title} (${v.formatDisplay})
- **3s Hook:** "${v.hook}"
- **Trend Driver:** ${v.whyTrending}
- **Predicted Impact:** ${v.predictedImpact.viralScore}/100 | ${v.predictedImpact.reachMultiplier}
- **Caption Template:**
${v.captionTemplate}
`).join('\n')}

## 4. 3-Tiered Hashtag Strategy
${report.hashtagClusters.map(c => `
### ${c.label}
${c.tags.map(t => `- ${t.tag} (${t.estimatedVolume})`).join('\n')}
`).join('\n')}

## 5. Posting Schedule & Guidelines
- **Prime Day & Time:** ${report.optimalPostingSchedule.primeDay} at ${report.optimalPostingSchedule.primeTimeWindow}
- **Recommended Frequency:** ${report.optimalPostingSchedule.frequencyPerWeek}
- **Rationale:** ${report.optimalPostingSchedule.explanation}

### Directives:
${report.algorithmDirectives.map(d => `- ${d}`).join('\n')}
`;

    navigator.clipboard.writeText(md);
    setCopiedMd(true);
    try {
      confetti({ particleCount: 25, spread: 45 });
    } catch {}
    setTimeout(() => setCopiedMd(false), 2000);
  };

  return (
    <Dialog open={true} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto p-6 border-zinc-800 bg-zinc-950 text-zinc-100">
        <DialogHeader className="text-left flex flex-row items-center justify-between pb-3 border-b border-zinc-800">
          <div>
            <Badge variant="outline" className="text-[10px] py-0 px-2 mb-1 border-zinc-700 bg-zinc-900 text-zinc-300">
              EXECUTIVE CLIENT REPORT
            </Badge>
            <DialogTitle className="text-lg font-semibold text-zinc-100">
              Content Intelligence Deck: @{profile.username}
            </DialogTitle>
          </div>
          <div className="flex items-center gap-2 mr-6">
            <Button variant="outline" size="sm" onClick={handleCopyMarkdown} className="text-xs h-8">
              {copiedMd ? <Check className="w-3.5 h-3.5 mr-1 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 mr-1" />}
              {copiedMd ? 'Copied' : 'Copy MD'}
            </Button>
            <Button variant="brand" size="sm" onClick={handlePrint} className="text-xs h-8">
              <Printer className="w-3.5 h-3.5 mr-1" />
              Print / Save PDF
            </Button>
          </div>
        </DialogHeader>

        <div className="space-y-4 text-xs text-zinc-300 pt-2 leading-relaxed">
          {/* Section 1 */}
          <div className="rounded-lg border border-zinc-800/80 bg-zinc-900/30 p-4 space-y-1.5">
            <div className="text-[10px] font-semibold text-zinc-400 uppercase tracking-wider">
              1. Audience Archetype
            </div>
            <div className="text-sm font-semibold text-zinc-100">
              {report.detectedNiche.primaryCategory} &bull; {report.detectedNiche.subNiche}
            </div>
            <p className="text-zinc-400">
              <span className="text-zinc-300 font-medium">Audience:</span> {report.detectedNiche.targetAudiencePersona}
            </p>
            <p className="text-zinc-400">
              <span className="text-zinc-300 font-medium">Tone:</span> {report.detectedNiche.contentTone}
            </p>
          </div>

          {/* Section 2 */}
          <div className="rounded-lg border border-zinc-800/80 bg-zinc-900/30 p-4 space-y-2">
            <div className="text-[10px] font-semibold text-zinc-400 uppercase tracking-wider">
              2. Algorithmic Signals
            </div>
            <div className="grid grid-cols-3 gap-2">
              <div className="p-2.5 rounded bg-zinc-950 border border-zinc-800">
                <div className="text-[10px] text-zinc-500">Engagement</div>
                <div className="text-base font-semibold text-zinc-100">{performance?.avgEngagementRate}%</div>
              </div>
              <div className="p-2.5 rounded bg-zinc-950 border border-zinc-800">
                <div className="text-[10px] text-zinc-500">Save-to-Reach</div>
                <div className="text-base font-semibold text-zinc-100">{performance?.saveToReachRatio}%</div>
              </div>
              <div className="p-2.5 rounded bg-zinc-950 border border-zinc-800">
                <div className="text-[10px] text-zinc-500">Top Format</div>
                <div className="text-base font-semibold text-zinc-100">{performance?.topPerformingFormat}</div>
              </div>
            </div>
          </div>

          {/* Section 3 */}
          <div className="rounded-lg border border-zinc-800/80 bg-zinc-900/30 p-4 space-y-2">
            <div className="text-[10px] font-semibold text-zinc-400 uppercase tracking-wider">
              3. Recommended Formats
            </div>
            <div className="space-y-1.5">
              {report.viralRecommendations.slice(0, 3).map((r, i) => (
                <div key={i} className="p-2.5 rounded bg-zinc-950 border border-zinc-800">
                  <div className="font-semibold text-zinc-200">
                    {i + 1}. {r.title} ({r.formatDisplay})
                  </div>
                  <div className="text-zinc-400 mt-0.5">&ldquo;{r.hook}&rdquo;</div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 4 */}
          <div className="rounded-lg border border-zinc-800/80 bg-zinc-900/30 p-4 space-y-1">
            <div className="text-[10px] font-semibold text-zinc-400 uppercase tracking-wider">
              4. Peak Timing &amp; Directives
            </div>
            <p className="text-zinc-300">
              <strong>Window:</strong> {report.optimalPostingSchedule.primeDay} @ {report.optimalPostingSchedule.primeTimeWindow} ({report.optimalPostingSchedule.frequencyPerWeek})
            </p>
            <ul className="list-disc pl-4 text-zinc-400 space-y-0.5 mt-1">
              {report.algorithmDirectives.map((d, i) => (
                <li key={i}>{d}</li>
              ))}
            </ul>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
